# Test Audio Sender

This file is used for sending audio data to the device. It measures the accuracy based on individual audio files.

**Note that the software on the MCU must match this!**

In [264]:
AUDIO_FOLDER_PATH = "./audio"
POSITIVE_PATH = f"{AUDIO_FOLDER_PATH}/positive"
NEGATIVE_PATH = f"{AUDIO_FOLDER_PATH}/negative"

In [265]:
import numpy as np
import pandas as pd
import gc
import os
import librosa
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
import serial
import struct

In [266]:
# Collecte positive audio files and their classes
positive_audio_files = []
positive_audio_file_classes = []
# Look each file in the audio folder
audio_class_folders = os.listdir(POSITIVE_PATH)
# Loop each class folder
for audio_class_folder in audio_class_folders:
    # Assemble full audio class folder path.
    audio_class_folder_path = os.path.join(POSITIVE_PATH, audio_class_folder)
    print("Processing class folder: ", audio_class_folder_path)
    # Get all files in the audio class folder
    audio_class_files = os.listdir(audio_class_folder_path)
    # Loop each audio file in the audio class folder
    for audio_class_file in audio_class_files:
        # Assemble full audio file path.
        audio_file_path = os.path.join(audio_class_folder_path, audio_class_file)
        # Append the audio file path to the positive_audio_files list
        positive_audio_files.append(audio_file_path)
        # Append the audio class to the audio_file_classes list
        positive_audio_file_classes.append(audio_class_folder)
print("positive_audio_files length: ", len(positive_audio_files))
print("positive_audio_file_classes length: ", len(positive_audio_file_classes))

Processing class folder:  ./audio/positive/Car
Processing class folder:  ./audio/positive/Comm
Processing class folder:  ./audio/positive/Motorcycle
positive_audio_files length:  9235
positive_audio_file_classes length:  9235


In [267]:
positive_audio_file_classes[0]

'Car'

In [268]:
# Collecte negative audio files and their classes
negative_audio_files = []
negative_audio_file_classes = []
# Look each file in the audio folder
audio_class_folders = os.listdir(NEGATIVE_PATH)
# Loop each class folder
for audio_class_folder in audio_class_folders:
    # Assemble full audio class folder path.
    audio_class_folder_path = os.path.join(NEGATIVE_PATH, audio_class_folder)
    print("Processing class folder: ", audio_class_folder_path)
    # Get all files in the audio class folder
    audio_class_files = os.listdir(audio_class_folder_path)
    # Loop each audio file in the audio class folder
    for audio_class_file in audio_class_files:
        # Assemble full audio file path.
        audio_file_path = os.path.join(audio_class_folder_path, audio_class_file)
        # Append the audio file path to the negative_audio_files list
        negative_audio_files.append(audio_file_path)
        # Append the audio class to the audio_file_classes list
        negative_audio_file_classes.append(audio_class_folder)
print("negative_audio_files length: ", len(negative_audio_files[0:10]))
print("negative_audio_file_classes length: ", len(negative_audio_file_classes[0:10]))

Processing class folder:  ./audio/negative/Background_noise
negative_audio_files length:  10
negative_audio_file_classes length:  10


In [269]:
# Shuffle the audio files and classes with the same seed.
seed = 42
np.random.seed(seed)
np.random.shuffle(positive_audio_files)

np.random.seed(seed)
np.random.shuffle(positive_audio_file_classes)

np.random.seed(seed)
np.random.shuffle(negative_audio_files)

np.random.seed(seed)
np.random.shuffle(negative_audio_file_classes)

In [270]:
# Hot end code the labels.
label_encoder = LabelEncoder()
positive_audio_file_classes_categorical = to_categorical(label_encoder.fit_transform(positive_audio_file_classes))
print("Example of audio_file_classes_categorial: ", positive_audio_file_classes_categorical[0:10])

Example of audio_file_classes_categorial:  [[0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [271]:
# Connect to MCU via serial.
print("Configuring serial port...")
ser = serial.Serial(
    port='/dev/ttyACM0',  # Change this to your actual port, e.g., 'COM3' on Windows, '/dev/ttyS0' on Linux
    baudrate=115200,       # Set baud rate to 115200
    bytesize=serial.EIGHTBITS,
    parity=serial.PARITY_NONE,
    stopbits=serial.STOPBITS_ONE,
    timeout=1              # Set timeout for reading
)

Configuring serial port...


In [272]:
if ser.is_open:
    print(f"Serial port {ser.port} opened at {ser.baudrate} baud.")

Serial port /dev/ttyACM0 opened at 115200 baud.


In [273]:
def calc_accuracy(y_true, y_pred, audioFilesProcessed):
    success = 0
    for i in range(len(y_pred)):
        if y_pred[i] == y_true[i]:
            success += 1
    res = round(success / audioFilesProcessed, 4)
    return res

In [274]:
audioSent = 0
audioFilesProcessed = 0
results = []
realResults = []

In [275]:
positive_audio_file_classes_categorical[0]

array([0., 1., 0.])

In [276]:
def streamAudioFile(file_path, i):
    global audioSent
    global results
    global realResults
    global positive_audio_file_classes_categorical
    global audioFilesProcessed
    numOfMaxTransferes = 20 * 4000
    audioFilesProcessed += 1
    # Check file format.
    if not file_path.endswith('.wav'):
        print("Error: Only .wav files are supported.")
        return
    # Load the audio file.
    audio_data, sr = librosa.load(file_path, sr=None)
    # Convert sample rate to 16kHz.
    if sr != 16000:
        audio_data = librosa.resample(y=audio_data, orig_sr=sr, target_sr=16000)
        sr = 16000
    # Convert the audio data to a numpy array.
    audio_data = np.array(audio_data, dtype=np.float32)
    # Send the audio data to the MCU.
    for j in range(len(audio_data)):
        numOfMaxTransferes = numOfMaxTransferes - 1
        if numOfMaxTransferes == 0:
            print("Error: Too many transfers. Next file.")
            return
        data_to_send = struct.pack('f', audio_data[j])
        ser.write(data_to_send)
        audioSent += 1
        if audioSent % 4000:
            while ser.in_waiting > 0:
                response = ser.readline().decode('utf-8').strip()
                # If response does not start with "f:"
                if response.startswith("e:"):
                    print(response)
                    return
                if response.startswith("c:"):
                    print(response)
                if response.startswith("s:"):
                    print(response)
                if response.startswith("v:"):
                    # Remove two first characters from the response.
                    response = int(response[2:])
                    realResults.append(np.argmax(positive_audio_file_classes_categorical[0][i]))
                    # Append the response to the results list.
                    results.append(response)
    print(f"Accuracy: {calc_accuracy(realResults, results, audioFilesProcessed)}")

In [277]:

total_positive_audio_files = len(positive_audio_files)

# Loop each audio file.
negative_audio_file_pointer = 0
for i in range(total_positive_audio_files):
    # Get audio file path.
    audio_file = positive_audio_files[i]
    # Print audio file path and class.
        #print("Processing audio file: ", audio_file)
        #print("Processing audio file class: ", positive_audio_file_classes[i])
    # Stream positive audio file to MCU.
        #streamAudioFile(audio_file, i)
    # Print nagtive audio file path and class.
    print("Processing negative audio file: ", negative_audio_files[negative_audio_file_pointer])
    print("Processing negative audio file class: ", negative_audio_file_classes[negative_audio_file_pointer])
    # Stream negative audio file to MCU.
    streamAudioFile(negative_audio_files[negative_audio_file_pointer], i)
    # Increment the negative audio file pointer.
    negative_audio_file_pointer += 1
    # Check if the negative audio file pointer is out of range.
    if negative_audio_file_pointer >= len(negative_audio_files):
        negative_audio_file_pointer = 0

Processing negative audio file:  ./audio/negative/Background_noise/346562__lebaston100__rain-without-thunder.wav
Processing negative audio file class:  Background_noise
s:Heap: 1096 / 462224 bytes
s:Tensor arena size: 36168/37000 bytes
s:Input tensor shape: 1, 16, 8, 1
s:Output tensor shape: 1, 4
s:0.149696 0.195662 -0.072511 0.049798 -0.074833 -0.068556 -0.114059 0.043434 0.108728 0.028366 0.005504 0.087522 0.091678 -0.312554 0.160393 0.241498 0.257499 -0.001246 -0.511153 -0.361162
s:0.188941 0.048005 -0.002183 -0.008556 0.081348 -0.095115 0.004988 0.065577 0.006750 0.080604 0.063035 0.034498 -0.013459 -0.041013 -0.071938 -0.108172 -0.013611 0.013356 -0.157677 -0.005753
s:0.058240 -0.059953 0.135505 0.147154 -0.071102 -0.050295 -0.031308 -0.039342 -0.001128 0.012287 -0.024849 -0.130801 -0.044181 0.198791 -0.120676 0.051826 0.113831 0.055619 -0.011331 -0.064862
s:0.037226 0.095239 0.079280 0.065427 0.038304 -0.047613 0.014771 0.055271 0.027971 -0.202824 -0.010529 -0.023211 -0.132829 0.

KeyboardInterrupt: 

In [ ]:
# Close the serial port
ser.close()